Disable sanitizers on release builds
viniciusferrao/cloysterhpc pull request #66
Opened 2024-08-19 22:08 UTC by arthurmco

The sanitizers works best on debug builds, they do not make sense on release and add unneeded dependencies

2024-08-19 23:07 UTC, lbgracioso commented
LGTM @arthurmco

2024-08-19 23:07 UTC, lbgracioso approved these changes

2024-08-20 00:37 UTC, viniciusferrao requested changes

2024-08-20 00:37 UTC, viniciusferrao commented on cmake/Hardening.cmake
> +    if(MINIMAL_RUNTIME AND CMAKE_BUILD_TYPE STREQUAL "Debug")
Here is if DEBUG. Seems reasonable.

2024-08-20 00:37 UTC, viniciusferrao commented on cmake/Sanitizers.cmake
> +    if(CMAKE_BUILD_TYPE STREQUAL "Release")
However here is: if RELEASE.

So `RelWithDebInfo` and `MinSizeRel` will be uncovered.

2024-08-20 18:13 UTC, merged