[CLOYSTER-108] Implement CPack
viniciusferrao/cloysterhpc pull request #70
Opened 2024-08-29 20:12 UTC by lbgracioso

Hey, this soon-to-be PR implements CPack.

I'm creating a draft because few things need to be discussed:

After running `cpack -g RPM`, we get our RPM file.

### If we check with `rpm -qip`
```
$ rpm -qip CloysterHPC-0.1.1-Linux-Debug-GNU-13.2.1.rpm 
Name        : cloysterhpc
Version     : 0.1.1
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : System Environment/Daemons
Size        : 25758201
License     : Apache-2.0
Signature   : (none)
Source RPM  : cloysterhpc-0.1.1-1.src.rpm
Build Date  : Thu 29 Aug 2024 04:53:01 PM -03
Build Host  : cloyster.if.ufrj.br
Relocations : /usr 
Vendor      : ferrao.net.br
URL         : https://github.com/viniciusferrao/cloysterhpc
Summary     : Cloyster HPC is a turnkey HPC cluster solution with an user-friendly installer
Description :
Cloyster HPC is a turnkey HPC cluster solution with an user-friendly installer.
```

- Vendor
I used "ferrao.net.br" as the vendor because I wasn't sure what to put there.

- Group
I chose "System Environment/Daemons," but then I found this [Fedora deprecation alert](https://fedoraproject.org/wiki/RPMGroups), and now I'm not sure if it's right to use it.

- Summary and Description
They are currently the same. Do we need to make them different?

### If we check with `rpm-qlp`
```
$ rpm -qlp CloysterHPC-0.1.1-Linux-Debug-GNU-13.2.1.rpm 
/usr/bin/main
/usr/lib/.build-id
/usr/lib/.build-id/a5
/usr/lib/.build-id/a5/e9fd15dec691780818d27135b8e3e8881e729e
/usr/share/CloysterHPC
/usr/share/CloysterHPC/CloysterHPCConfig.cmake
/usr/share/CloysterHPC/CloysterHPCConfigVersion.cmake
/usr/share/CloysterHPC/CloysterHPCTargets-debug.cmake
/usr/share/CloysterHPC/CloysterHPCTargets.cmake
/usr/share/CloysterHPC/usage
```

- Binary name
As you can see, the binary is named **main**. What should it be named instead?

### RPM filename
So, `CloysterHPC-0.1.1-Linux-Debug-GNU-13.2.1.rpm`. As you can see, **I removed the GIT-SHA**. Why?
Simply because it was appearing as **Unknown**.
Are we actually using it? If so, I need to put it back. If not, I need to remove the old documentation I left.

I think that's everything.

### Tasks
- [x] Decide **binary name**
- [x] Decide **vendor**
- [x] Decide if **group** will be used or not. If yes, decide group name.
- [x] Decide whether the **summary** and **description** should be different.
- [x] Decide if **GIT-SHA** will appear in the binary name.

2024-08-29 20:22 UTC, arthurmco commented
Well, my 2 cents

 - Binary name should be cloyster (in the future we might want to add two: the installer, named `cloyster`, and the daemon, named `cloysterd`
 - Vendor should be VersatusHPC
 - I liked the description, not so sure about the name
 - It seems that they are deprecating the groups entirely. We should add no group, then.
 - I think it's better for the SHA to be added in the version, if possible. If not, we must add the GIT SHA somewhere in the app (maybe informed by some --version parameter) so we can know in what commit the software installed in the user's cluster was built.

2024-08-29 20:23 UTC, lbgracioso commented
@arthurmco, I thought VersatusHPC might not be a good idea because this repository deals with Cloyster, not OpenCATTUS.

The other suggestions sound good to me; I like them.

2024-09-02 14:58 UTC, viniciusferrao requested changes
Great PR.

I'm missing information like where the binary will be installed. I think we should use `/opt/cloysterhpc/sbin`

I don't know exactly what `Relocations : /usr` means.

It's also missing the signature.

Finally I think this files should not be shipped:
```
/usr/lib/.build-id
/usr/lib/.build-id/a5
/usr/lib/.build-id/a5/e9fd15dec691780818d27135b8e3e8881e729e
/usr/share/CloysterHPC
/usr/share/CloysterHPC/CloysterHPCConfig.cmake
/usr/share/CloysterHPC/CloysterHPCConfigVersion.cmake
/usr/share/CloysterHPC/CloysterHPCTargets-debug.cmake
/usr/share/CloysterHPC/CloysterHPCTargets.cmake
```

Do we have control over it?

2024-09-02 14:58 UTC, viniciusferrao commented on cmake/CPackProperties.cmake
> +set(CPACK_PACKAGE_VENDOR "ferrao.net.br")
```suggestion
set(CPACK_PACKAGE_VENDOR "CloysterHPC")
```

2024-09-02 14:58 UTC, viniciusferrao commented on cmake/CPackProperties.cmake
> +set(CPACK_RPM_PACKAGE_GROUP "System Environment/Daemons")
```suggestion
```

2024-09-02 14:58 UTC, viniciusferrao commented on cmake/CPackProperties.cmake
> +# set(CPACK_RPM_PACKAGE_REQUIRES "") # We need to figure out what dependencies Cloyster requires
Basically `newt`.

For the release build it should be sufficient.

2024-09-02 19:51 UTC, lbgracioso commented
> Great PR.
> 
> I'm missing information like where the binary will be installed. I think we should use `/opt/cloysterhpc/sbin`

Great, I will change it.

> I don't know exactly what `Relocations : /usr` means.

About "_Relocations_", you can check it [here](http://ftp.rpm.org/api/4.4.2.2/relocatable.html).
_Relocatable packages are a way to give the user a little control over the installation location of a package. For example, a vendor may distribute their software to install in "/opt" but you'd like it to install in "/usr/opt". If the vendor were distributing a relocatable RPM package, it would be easy_.

> It's also missing the signature.

Can you check this [here](https://access.redhat.com/articles/3359321) and prepare the environment for it, please?

> Finally I think this files should not be shipped:
> 
> ```
> /usr/lib/.build-id
> /usr/lib/.build-id/a5
> /usr/lib/.build-id/a5/e9fd15dec691780818d27135b8e3e8881e729e
> /usr/share/CloysterHPC
> /usr/share/CloysterHPC/CloysterHPCConfig.cmake
> /usr/share/CloysterHPC/CloysterHPCConfigVersion.cmake
> /usr/share/CloysterHPC/CloysterHPCTargets-debug.cmake
> /usr/share/CloysterHPC/CloysterHPCTargets.cmake
> ```
> 
> Do we have control over it?

I'll check it. Probably they are specified under  `install()` operation somewhere in CMake.

2024-09-03 11:54 UTC, lbgracioso commented
So far, I have some updates.

## cpack-g RPM & rpm -qlip
```
[lbgracioso@cloyster cmake-build-debug-cloysterdev-ifufrj]$ sudo cpack -g RPM 
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: CloysterHPC
CPack: - Install project: CloysterHPC []
CPack: -   Install component: bin
CPack: Create package
CPackRPM: Will use GENERATED spec file: /tmp/cloyster-lbgracioso/cmake-build-debug-cloysterdev-ifufrj/_CPack_Packages/Linux/RPM/SPECS/cloysterhpc-bin.spec
CPack: - package: /tmp/cloyster-lbgracioso/cmake-build-debug-cloysterdev-ifufrj/CloysterHPC-0.1.1-Unknown-Linux-Debug-GNU-13.2.1-bin.rpm generated.
[lbgracioso@cloyster cmake-build-debug-cloysterdev-ifufrj]$ rpm -qlip CloysterHPC-0.1.1-Unknown-Linux-Debug-GNU-13.2.1-bin.rpm 
Name        : cloysterhpc-bin
Version     : 0.1.1
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : unknown
Size        : 25748192
License     : Apache-2.0
Signature   : (none)
Source RPM  : cloysterhpc-bin-0.1.1-1.src.rpm
Build Date  : Tue 03 Sep 2024 08:50:37 AM -03
Build Host  : cloyster.if.ufrj.br
Relocations : /usr 
Vendor      : CloysterHPC
URL         : https://github.com/viniciusferrao/cloysterhpc
Summary     : Cloyster HPC is a turnkey HPC cluster solution with an user-friendly installer
Description :
Cloyster HPC is a turnkey HPC cluster solution with an user-friendly installer.
/usr/lib/.build-id
/usr/lib/.build-id/bb
/usr/lib/.build-id/bb/7a0c9512f8a494c01789b946149b02b1d4c8d7
/usr/opt
/usr/opt/CloysterHPC
/usr/opt/CloysterHPC/sbin
/usr/opt/CloysterHPC/sbin/cloysterhpc
```

## Tasks
- [ ] Make git-sha usable (now it appears as Unknown)
- [ ] Remove `/usr/lib*` from the rpm
- [ ] Change RPM name back to `cloysterhpc` (instead of `cloysterhpc-bin`) and filename without `-bin` in the end.

2024-09-04 23:10 UTC, viniciusferrao commented
Lucas if it's too hard to remove the garbage that CMake left on the filesystem we can ignore it. It's not ideal, but it's also not big deal.

2024-09-05 14:43 UTC, viniciusferrao requested changes
Everything seems fine, that's just one block of deletes that we should do otherway, to keep compatibility with upstream.

2024-09-05 15:07 UTC, lbgracioso commented on cmake/PackageProject.cmake
Done!

2024-09-05 15:23 UTC, merged